name: "Infra: Image Testing: Deploy"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag to use when manually publishing an image'
        required: false
  pull_request:
    types: ['labeled']

permissions:
  contents: read
  pull-requests: write
  packages: write

jobs:
  metadata:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'status/image_testing') }}
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.collect.outputs.tag }}
      sha: ${{ steps.collect.outputs.sha }}
    steps:
      - id: collect
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "tag=pr${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            manual_tag="${{ github.event.inputs.tag }}"
            if [ -z "$manual_tag" ]; then
              manual_tag="manual-${GITHUB_RUN_ID}"
            fi
            echo "tag=$manual_tag" >> $GITHUB_OUTPUT
            echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

  jar-build:
    needs: metadata
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # infered from @v4
        with:
          ref: ${{ needs.metadata.outputs.sha }}
          token: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # infered from @v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build jar
        id: build
        run: |
          version=${{ needs.metadata.outputs.tag }}
          echo "version=$version" >> $GITHUB_OUTPUT
          ./gradlew clean build \
            -x test \
            -Pinclude-frontend=true \
            -Pversion=$version

      - name: Upload jar
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # infered from @v4
        with:
          name: kafbat-ui-${{ steps.build.outputs.version }}
          path: api/build/libs/api-${{ steps.build.outputs.version }}.jar
          retention-days: 1

  docker-build:
    needs: [ metadata, jar-build ]
    permissions:
      contents: read
    uses: ./.github/workflows/docker_build.yml
    secrets: inherit
    with:
      sha: ${{ needs.metadata.outputs.sha }}
      version: ${{ needs.jar-build.outputs.version }}

  docker-deploy:
    needs: [ metadata, jar-build, docker-build ]
    permissions:
      packages: write
    uses: ./.github/workflows/docker_publish.yml
    secrets: inherit
    with:
      version: ${{ needs.jar-build.outputs.version }}
      generic_tag: ${{ needs.metadata.outputs.tag }}
      registries: '["ghcr.io"]'
      repository: ${{ format('{0}/kafbat-ui-features', github.repository_owner) }}

  notify:
    needs: [ metadata, docker-deploy ]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: make comment with image link
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # infered from @v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Image published at ghcr.io/${{ format('{0}/kafbat-ui-features', github.repository_owner) }}:${{ needs.metadata.outputs.tag }}
